project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!manuscript.qmd"

freeze: auto 

website:
  title: "LLM Predictions Megastudy"
  description: "Predicting behavioral intervention effects on humans with LLM clones"
  favicon: ""
  page-footer:
    center: "Jan Pfänder · 2026"
  navbar:
    background: dark
    foreground: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Preregistration"
        href: preregistration.qmd
      - text: "Generate profiles from GSS"
        href: clone_profiles/make_profiles.qmd
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: right
    code-tools: true
    smooth-scroll: true
    link-external-newwindow: true

bibliography: bibliography.bib
